### ISSUE TITLE
使用說明不顯眼問題

### ISSUE THREAD

**Issue by seadog007** [TakeshiTseng/SitconSeatingChart#8]
建議利用Cookie讓第一次使用的使用者直接跳使用說明
不然使用說明一定會被無視
第一次瀏覽過後help=1
然後遇到沒Cookie之類的話就直接噴使用說明

**Comment by TakeshiTseng** [comment]
Fixed

**Comment by iblis17** [comment]
@TakeshiTseng 何不 refer 一下 commit?

**Comment by iblis17** [comment]
像是 #3

**Comment by TakeshiTseng** [comment]
這個？ @996f9bf

**Comment by seadog007** [comment]
就是commit的時候可以加在commit name

**Comment by iblis17** [comment]
@TakeshiTseng  https://guides.github.com/features/issues/
https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by TakeshiTseng** [comment]
Got it

**Comment by seadog007** [comment]
是說ref到了 # 3了

**Comment by iblis17** [comment]
目前 cookie 壞了？
Express
500 Error: `secret` option required for cookie sessions

    at Object.cookieSession [as handle] (/root/git/SitconSeatingChart/node_modules/express/node_modules/connect/lib/middleware/cookieSession.js:61:24)
    at next (/root/git/SitconSeatingChart/node_modules/express/node_modules/connect/lib/proto.js:193:15)
    at Object.cookieParser [as handle] (/root/git/SitconSeatingChart/node_modules/express/node_modules/connect/lib/middleware/cookieParser.js:65:5)
    at next (/root/git/SitconSeatingChart/node_modules/express/node_modules/connect/lib/proto.js:193:15)
    at Object.methodOverride [as handle] (/root/git/SitconSeatingChart/node_modules/express/node_modules/connect/lib/middleware/methodOverride.js:48:5)
    at next (/root/git/SitconSeatingChart/node_modules/express/node_modules/connect/lib/proto.js:193:15)
    at Object.urlencoded [as handle] (/root/git/SitconSeatingChart/node_modules/express/node_modules/connect/lib/middleware/urlencoded.js:41:37)
    at next (/root/git/SitconSeatingChart/node_modules/express/node_modules/connect/lib/proto.js:193:15)
    at Object.json [as handle] (/root/git/SitconSeatingChart/node_modules/express/node_modules/connect/lib/middleware/json.js:42:37)
    at next (/root/git/SitconSeatingChart/node_modules/express/node_modules/connect/lib/proto.js:193:15)

**Comment by TakeshiTseng** [comment]
有新增一個 cookieSecret 的設定在 config.js 裡面，參考 a05d12c

**Comment by iblis17** [comment]
ok @TakeshiTseng 下次可以用 commit close issue

**Comment by TakeshiTseng** [comment]
OK
